
version: "3.7"

networks:
  feature-flags:

services:
  db:
    image: postgres:12
    # restart: always
    container_name: db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=feature-flags-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpw
    networks:
      - feature-flags

#  adminer:
#    image: adminer
#    restart: always
#    container_name: adminer
#    ports:
#      - 8080:8080
#    networks:
#      - feature-flags
