
version: "3.7"

networks:
  feature-flags:

services:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=feature-flags-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpw
    networks:
      - feature-flags
