kumuluzee:
  name: lokacijski-opomniki-jpa
  version: 1.0.0
  server:
    http:
      port: 8081
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/feature-flags
      connection-url: jdbc:postgresql://localhost:5433/feature-flags-db
      username: postgres
      password: adminpw
      pool:
        max-size: 20
